services:
  - type: web
    name: wallet-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: wallet-app-db
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 3000

databases:
  - name: wallet-app-db
    plan: free
    ipAllowList: []
